image:
   file: ./gitpod/gitpod.Dockerfile

tasks:
  - command: docker ps
  - command: terraform version


ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
  - hashicorp.terraform
  - ms-python.python