image:
  file: gitpod/gitpod.Dockerfile

tasks:
  - command: docker ps
  - command: terraform version
  - command: gp env BLUECODING=engineer

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
  - hashicorp.terraform
  - ms-python.python
