image:
  file: gitpod/gitpod.Dockerfile

tasks:
  - command: docker ps
  - command: terraform version
  - command: gp env BLUECODING=engineer
  - command: gp env PS1='> '

ports:
  - port: 8080
    onOpen: open-preview
  - port: 8081-8090
    onOpen: ignore

vscode:
  extensions:
  - hashicorp.terraform
  - ms-python.python
